services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="$HOME/.local/bin:$PATH"
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    environment:
      pythonVersion: 3.11.9
    envVars:
      - key: BOT_TOKEN
        sync: false
